// src/help-texts.js

export const helpTexts = {
  ls: [
    "Usage: ls",
    "",
    "List directory contents.",
    "",
    "Examples:",
    "  ls        List files in current directory",
    "  ls --help Show this help",
  ],

  cd: [
    "Usage: cd [directory]",
    "",
    "Change the current directory.",
    "",
    "Arguments:",
    "  directory    Path (use .. for parent, / for root)",
    "",
    "Examples:",
    "  cd docs      Navigate to docs folder",
    "  cd ..        Go to parent directory",
    "  cd /         Go to root directory",
    "  cd --help    Show this help",
  ],

  help: [
    "Usage: help [command]",
    "",
    "Show available commands or help for specific command.",
    "",
    "Arguments:",
    "  command      Optional command name",
    "",
    "Examples:",
    "  help         Show all commands",
    "  help ls      Show help for ls",
    "  help --help  Show this help",
  ],

  clear: [
    "Usage: clear",
    "",
    "Clear the terminal screen.",
    "",
    "Aliases:",
    "  cls          Same as clear",
    "",
    "Examples:",
    "  clear        Clear screen",
    "  cls          Clear screen",
    "  clear --help Show this help",
  ],

  cls: [
    "Usage: cls",
    "",
    "Clear the terminal screen.",
    "",
    "Aliases:",
    "  clear        Same as cls",
    "",
    "Examples:",
    "  cls          Clear screen",
    "  clear        Clear screen",
    "  cls --help   Show this help",
  ],

  logout: [
    "Usage: logout",
    "",
    "Log out from current user and return to guest.",
    "",
    "Examples:",
    "  logout       Log out to guest account",
    "  logout --help Show this help",
  ],

  mkdir: [
    "Usage: mkdir <directory>",
    "",
    "Create new directory.",
    "",
    "Examples:",
    "  mkdir projects",
    "  mkdir --help",
  ],

  rmdir: [
    "Usage: rmdir <directory>",
    "",
    "Remove an empty directory.",
    "",
    "Examples:",
    "  rmdir test",
    "  rmdir --help",
    "",
    "Note: Directory must be empty",
  ],

  rm: [
    "Usage: rm [-r] <file|directory>",
    "",
    "Remove files or directories.",
    "",
    "Options:",
    "  -r, -R      Remove directories recursively",
    "",
    "Examples:",
    "  rm file.txt       Remove a file",
    "  rm -r folder      Remove folder (even if not empty)",
    "  rm --help         Show this help",
    "",
    "Warning: Recursive removal is permanent!",
  ],

  reboot: [
    "Usage: reboot",
    "",
    "Restart the terminal session.",
    "",
    "Warning:",
    "  This clears session and logs you out",
    "",
    "Examples:",
    "  reboot       Restart system",
    "  reboot --help Show this help",
  ],

  time: [
    "Usage: time",
    "",
    "Display current date and time.",
    "",
    "Aliases:",
    "  clock        Same as time",
    "",
    "Examples:",
    "  time         Show current date/time",
    "  clock        Show current date/time",
    "  time --help  Show this help",
  ],

  clock: [
    "Usage: clock",
    "",
    "Display current date and time.",
    "",
    "Aliases:",
    "  time         Same as clock",
    "",
    "Examples:",
    "  clock        Show current date/time",
    "  time         Show current date/time",
    "  clock --help Show this help",
  ],

  version: [
    "Usage: version",
    "",
    "Display NextOS version information.",
    "",
    "Aliases:",
    "  ver          Same as version",
    "",
    "Examples:",
    "  version      Show version",
    "  ver          Show version",
    "  version --help Show this help",
  ],

  ver: [
    "Usage: ver",
    "",
    "Display NextOS version information.",
    "",
    "Aliases:",
    "  version      Same as ver",
    "",
    "Examples:",
    "  ver          Show version",
    "  version      Show version",
    "  ver --help   Show this help",
  ],

  vi: [
    "Usage: vi <filename>",
    "",
    "Vi-style text editor.",
    "",
    "Normal mode commands:",
    "  i       Enter insert mode",
    "  j/k     Move down/up",
    "  o/O     New line below/above",
    "  dd      Delete line",
    "  :w      Save file",
    "  :q      Quit",
    "  :wq     Save and quit",
    "  :q!     Quit without saving",
    "",
    "Insert mode:",
    "  ESC     Return to normal mode",
    "  Type to insert text",
    "",
    "Aliases: vim",
  ],

  login: [
    "Usage: login",
    "",
    "Start login process to authenticate as user.",
    "",
    "Process:",
    "  1. Enter username",
    "  2. Enter password (hidden)",
    "  3. Access granted if correct",
    "",
    "Examples:",
    "  login        Start login",
    "  login --help Show this help",
  ],

  theme: [
    "Usage: theme [name]",
    "",
    "Change or view current terminal theme.",
    "",
    "Arguments:",
    "  name         Theme name",
    "",
    "Available themes:",
    "  matrix, ocean, sunset, hacker, retro",
    "",
    "Examples:",
    "  theme        Show current theme",
    "  theme matrix Switch to matrix",
    "  theme --help Show this help",
  ],
};
