// src/help-texts.js

export const helpTexts = {
  ls: [
    "Usage: ls [options]",
    "",
    "List directory contents.",
    "",
    "Options:",
    "  --help    Show this help message",
    "",
    "Examples:",
    "  ls        List files in current directory",
  ],

  cd: [
    "Usage: cd [directory]",
    "",
    "Change the current directory.",
    "",
    "Arguments:",
    "  directory    Path to navigate to (use .. for parent, / for root)",
    "",
    "Options:",
    "  --help       Show this help message",
    "",
    "Examples:",
    "  cd docs      Navigate to docs folder",
    "  cd ..        Go to parent directory",
    "  cd /         Go to root directory",
  ],

  help: [
    "Usage: help [command]",
    "",
    "Show available commands or help for a specific command.",
    "",
    "Arguments:",
    "  command    Optional: show help for specific command",
    "",
    "Options:",
    "  --help     Show this help message",
    "",
    "Examples:",
    "  help       Show all commands",
    "  help ls    Show help for ls command",
  ],

  clear: [
    "Usage: clear",
    "",
    "Clear the terminal screen.",
    "",
    "Options:",
    "  --help    Show this help message",
    "",
    "Aliases: cls",
  ],

  logout: [
    "Usage: logout",
    "",
    "Log out from current user and return to guest.",
    "",
    "Options:",
    "  --help    Show this help message",
  ],

  reboot: [
    "Usage: reboot",
    "",
    "Restart the terminal session.",
    "",
    "Options:",
    "  --help    Show this help message",
  ],

  time: [
    "Usage: time",
    "",
    "Display current date and time.",
    "",
    "Options:",
    "  --help    Show this help message",
    "",
    "Aliases: clock",
  ],

  version: [
    "Usage: version",
    "",
    "Display NextOS version information.",
    "",
    "Options:",
    "  --help    Show this help message",
    "",
    "Aliases: ver",
  ],

  login: [
    "Usage: login",
    "",
    "Start the login process to authenticate as a user.",
    "",
    "Options:",
    "  --help    Show this help message",
  ],

  theme: [
    "Usage: theme [name]",
    "",
    "Change or view the current terminal theme.",
    "",
    "Arguments:",
    "  name       Theme name (matrix, ocean, sunset, hacker, retro)",
    "",
    "Options:",
    "  --help     Show this help message",
    "",
    "Examples:",
    "  theme           Show current theme",
    "  theme matrix    Switch to matrix theme",
    "  theme ocean     Switch to ocean theme",
  ],
};
